import type { IPO } from "../types/ipo"

export const mockIPOData: IPO[] = [
  {
    id: 1,
    company_name: "OLA Electric Mobility Ltd.",
    logo: "OLA",
    price_band: "₹72-76",
    open_date: "2024-08-02",
    close_date: "2024-08-06",
    issue_size: "₹5,500 Cr.",
    issue_type: "Book Built",
    listing_date: "2024-08-09",
    status: "listed",
    ipo_price: 76,
    listing_price: 85,
    current_market_price: 92,
    listing_gain: 11.84,
    current_return: 21.05,
    rhp_pdf: "/docs/ola-rhp.pdf",
    drhp_pdf: "/docs/ola-drhp.pdf",
  },
  {
    id: 2,
    company_name: "One Mobikwik Systems Ltd.",
    logo: "M",
    price_band: "₹265-279",
    open_date: "2024-12-11",
    close_date: "2024-12-13",
    issue_size: "₹1,900 Cr.",
    issue_type: "Book Built",
    listing_date: "2024-12-18",
    status: "ongoing",
    ipo_price: 279,
    rhp_pdf: "/docs/mobikwik-rhp.pdf",
    drhp_pdf: "/docs/mobikwik-drhp.pdf",
  },
  {
    id: 3,
    company_name: "Le Travenues Technology (ixigo)",
    logo: "ixigo",
    price_band: "₹88-93",
    open_date: "2024-06-10",
    close_date: "2024-06-12",
    issue_size: "₹1,800 Cr.",
    issue_type: "Book Built",
    listing_date: "2024-06-18",
    status: "listed",
    ipo_price: 93,
    listing_price: 106,
    current_market_price: 125,
    listing_gain: 13.98,
    current_return: 34.41,
    rhp_pdf: "/docs/ixigo-rhp.pdf",
    drhp_pdf: "/docs/ixigo-drhp.pdf",
  },
  {
    id: 4,
    company_name: "CMR Green Technologies",
    logo: "CMR",
    price_band: "₹200-220",
    open_date: "2025-01-15",
    close_date: "2025-01-17",
    issue_size: "₹500 Cr.",
    issue_type: "Book Built",
    status: "upcoming",
    rhp_pdf: "/docs/cmr-rhp.pdf",
    drhp_pdf: "/docs/cmr-drhp.pdf",
  },
  {
    id: 5,
    company_name: "Wellness Forever",
    logo: "W",
    price_band: "₹300-350",
    open_date: "2025-02-01",
    close_date: "2025-02-03",
    issue_size: "₹800 Cr.",
    issue_type: "Book Built",
    status: "upcoming",
    rhp_pdf: "/docs/wellness-rhp.pdf",
    drhp_pdf: "/docs/wellness-drhp.pdf",
  },
  {
    id: 6,
    company_name: "PKH Ventures Ltd.",
    logo: "PKH",
    price_band: "₹150-180",
    open_date: "2025-01-20",
    close_date: "2025-01-22",
    issue_size: "₹400 Cr.",
    issue_type: "Book Built",
    status: "upcoming",
    rhp_pdf: "/docs/pkh-rhp.pdf",
    drhp_pdf: "/docs/pkh-drhp.pdf",
  },
  {
    id: 7,
    company_name: "Nova Agritech Ltd.",
    logo: "NOVA",
    price_band: "₹39-41",
    open_date: "2024-01-22",
    close_date: "2024-01-24",
    issue_size: "₹38 Cr.",
    issue_type: "Book Built",
    listing_date: "2024-01-30",
    status: "listed",
    ipo_price: 41,
    listing_price: 45,
    current_market_price: 52,
    listing_gain: 9.76,
    current_return: 26.83,
    rhp_pdf: "/docs/nova-rhp.pdf",
    drhp_pdf: "/docs/nova-drhp.pdf",
  },
  {
    id: 8,
    company_name: "EPACK Durable Ltd.",
    logo: "E",
    price_band: "₹218-230",
    open_date: "2024-01-19",
    close_date: "2024-01-23",
    issue_size: "₹640.05 Cr.",
    issue_type: "Book Built",
    listing_date: "2024-01-29",
    status: "listed",
    ipo_price: 230,
    listing_price: 252,
    current_market_price: 275,
    listing_gain: 9.57,
    current_return: 19.57,
    rhp_pdf: "/docs/epack-rhp.pdf",
    drhp_pdf: "/docs/epack-drhp.pdf",
  },
]
